#**K-Nearest Neighbors (KNN)**

In [ ]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
from sklearn.preprocessing import LabelEncoder, StandardScaler
import matplotlib.pyplot as plt

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
path="/content/drive/MyDrive/ML Dataset/dataset.csv"
df = pd.read_csv(path)

df.head()

,Disease,Symptom_1,Symptom_2,Symptom_3,Symptom_4,Symptom_5,Symptom_6,Symptom_7,Symptom_8,Symptom_9,Symptom_10,Symptom_11,Symptom_12,Symptom_13,Symptom_14,Symptom_15,Symptom_16,Symptom_17
0,Fungal infection,itching,skin_rash,nodal_skin_eruptions,dischromic _patches,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Fungal infection,skin_rash,nodal_skin_eruptions,dischromic _patches,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Fungal infection,itching,nodal_skin_eruptions,dischromic _patches,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Fungal infection,itching,skin_rash,dischromic _patches,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Fungal infection,itching,skin_rash,nodal_skin_eruptions,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN


In [ ]:
df = df.replace("None", 0)
df = df.fillna(0)

In [ ]:
symptom_columns = df.columns.drop('Disease')

for col in symptom_columns:
    df[col] = df[col].apply(lambda x: 0 if x == 0 else 1)

In [ ]:
le = LabelEncoder()
df['Disease'] = le.fit_transform(df['Disease'])

In [ ]:
X = df.drop('Disease', axis=1)
y = df['Disease']

In [ ]:
X_train_70, X_test_30, y_train_70, y_test_30 = train_test_split(
    X, y, test_size=0.3, random_state=42
)

In [ ]:
scaler = StandardScaler()

X_train_70 = scaler.fit_transform(X_train_70)
X_test_30 = scaler.transform(X_test_30)

In [ ]:
model_70 = KNeighborsClassifier(n_neighbors=6)
model_70.fit(X_train_70, y_train_70)

KNeighborsClassifier(n_neighbors=6)

In [ ]:
y_pred_70 = model_70.predict(X_test_30)

In [ ]:
print("===== 70-30 Results =====")

print("Accuracy:", accuracy_score(y_test_30, y_pred_70))
print("Precision:", precision_score(y_test_30, y_pred_70, average='weighted'))
print("Recall:", recall_score(y_test_30, y_pred_70, average='weighted'))
print("F1 Score:", f1_score(y_test_30, y_pred_70, average='weighted'))
print("Confusion Matrix:\n", confusion_matrix(y_test_30, y_pred_70))

===== 70-30 Results =====
Accuracy: 0.21002710027100271
Precision: 0.102122901928248
Recall: 0.21002710027100271
F1 Score: 0.1233772298613584
Confusion Matrix:
 [[18  0  0 ...  0  0  0]
 [ 0 22  0 ...  0  0  0]
 [ 0 29  0 ...  0  0  0]
 ...
 [ 0 19  0 ...  0  0  0]
 [19  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]]


/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [ ]:
X_train_80, X_test_20, y_train_80, y_test_20 = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [ ]:
scaler = StandardScaler()

X_train_80 = scaler.fit_transform(X_train_80)
X_test_20 = scaler.transform(X_test_20)

In [ ]:
model_80 = KNeighborsClassifier(n_neighbors=6)
model_80.fit(X_train_80, y_train_80)

KNeighborsClassifier(n_neighbors=6)

In [ ]:
y_pred_80 = model_80.predict(X_test_20)

In [ ]:
print("===== 80-20 Results =====")

print("Accuracy:", accuracy_score(y_test_20, y_pred_80))
print("Precision:", precision_score(y_test_20, y_pred_80, average='weighted'))
print("Recall:", recall_score(y_test_20, y_pred_80, average='weighted'))
print("F1 Score:", f1_score(y_test_20, y_pred_80, average='weighted'))
print("Confusion Matrix:\n", confusion_matrix(y_test_20, y_pred_80))

===== 80-20 Results =====
Accuracy: 0.17886178861788618
Precision: 0.11029571105259003
Recall: 0.17886178861788618
F1 Score: 0.11467621642789122
Confusion Matrix:
 [[ 0  0  0 ...  0  0  0]
 [ 0  0 14 ...  0  0  0]
 [ 0  0  6 ...  0  0  0]
 ...
 [ 0  0 13 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]]


/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
